### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by hutao568** [PJLab-ADG/DetZero#1]
Dear Sir/Madam, I am very interested in your research work, I would like to know when you will release the code?

**Comment by zhaowenZhou** [comment]
Same here, looking forward to your code!

**Comment by superkoma** [comment]
Thanks for your interest in our work. We are cleaning the code recently and will release the code within 1~2 weeks.

**Comment by wellneck** [comment]
Same same here, looking forward to your code!

**Comment by hutao568** [comment]
Is it possible for your team to open source DetZero? @superkoma

**Comment by wateryzephyr** [comment]
Hm.

**Comment by Gabendi** [comment]
Hm.
