### ISSUE TITLE
“ModuleNotFoundError: No module named 'detzero_utils'”

### ISSUE THREAD

**Issue by rockywind** [PJLab-ADG/DetZero#10]
Hi, 
I met the error below when I run the script ```` python -m detzero_det.datasets.waymo.waymo_preprocess --cfg_file tools/cfgs/det_dataset_cfgs/waymo_one_sweep.yaml --func create_waymo_database````
I found the are no detzero_utils file.
![image](https://github.com/PJLab-ADG/DetZero/assets/14838781/22441ff5-e38a-4bec-8a1a-fa1eacb421b4)

**Comment by datouready** [comment]
Hi,You can find this file at location  DetZero-main/utils/detzero_utils

**Comment by rockywind** [comment]
thanks a lot!
