### ISSUE TITLE
the waymo dataset

### ISSUE THREAD

**Issue by SISTMrL** [PJLab-ADG/DetZero#12]
hello, i'm new to this field, could you please give some illustrations on how to obtain "imagesets" and "raw data", i see the waymo dataset only has some zip files. and i see many versions of dataset, what specific version datasets you have used in this work
![image](https://github.com/PJLab-ADG/DetZero/assets/47938053/3fc35542-bee4-40c8-85bf-e2508eaf649d)

**Comment by superkoma** [comment]
- ImageSets folder is used for determining the split of training, validation, and testing, which is already provided by our repo.
- Please download the v1.2 version for raw data, see the details at https://waymo.com/open/download/.
