### ISSUE TITLE
the processing time of waymo infos

### ISSUE THREAD

**Issue by SISTMrL** [PJLab-ADG/DetZero#14]
hello, when i run the code of 

cd detection
python -m detzero_det.datasets.waymo.waymo_preprocess --cfg_file tools/cfgs/det_dataset_cfgs/waymo_one_sweep.yaml --func create_waymo_infos

The program output log stayed in this interface for a long time, could you please tell me how long of the porcessing on waymo infos?
![image](https://github.com/PJLab-ADG/DetZero/assets/47938053/ff908a6d-2aeb-4e4a-9e63-abd0fb4d431e)

and the gpu memory i used is shown as below:
![image](https://github.com/PJLab-ADG/DetZero/assets/47938053/999f92ac-30df-47e8-b7c1-71e517dc2229)

**Comment by qinhuan** [comment]
@SISTMrL Hi，I encountered the same issue. How long does this process take? thanks

**Comment by qinhuan** [comment]
detection/detzero_det/datasets/waymo/waymo_utils.py,    save_data_worker This function takes a lot of time, and I can print the processing results of this function as a log. It will take me about 3 days to process the data
