### ISSUE TITLE
data association

### ISSUE THREAD

**Issue by SISTMrL** [PJLab-ADG/DetZero#15]
你好，我在看你的二阶段associations代码，发现在二阶段的时候为啥在line122把未匹配到的检测换成一阶段未匹配到的，而不是用line108的det_unmatch

![image](https://github.com/PJLab-ADG/DetZero/assets/47938053/6387a8d1-fb18-4004-bd03-9028c3a04ca4)

**Comment by suojinhui** [comment]
I also want to know. May I ask if you understand?

**Comment by suojinhui** [comment]
I think I've got it. detunmatch is used to initialize new trackers, using only high-quality unmatched detection boxes. The two-stage det boxes are those with low point nums and low confidence. If they don't match the anything tracks, they can be directly discarded.
