### ISSUE TITLE
GPU and GPU memery

### ISSUE THREAD

**Issue by Coincidance-Levi** [PJLab-ADG/DetZero#2]
Very good works you done!
For better evaluation and estimation on your models, could you share what GPU you used, which seems not mentioned in your paper, and also the approximate memory occupied by each GPU?

**Comment by superkoma** [comment]
Thanks for your reminder, we will provide the details in README.md of the next version.

**Comment by YoushaaMurhij** [comment]
@superkoma, I am still confused about the minimun GPU / CPU and RAM requiremetns to train this model!
Could please provide an estimation? 
I tried to start the training process and noticed that the used GPU memory did not incease (~400 mb)  while RAM usage kept increasing until it reached 128GB (and crashed -- no more RAM available).
I used dist_train on 2 gpu devices.
Thanks!
