### ISSUE TITLE
refine result visualization error.

### ISSUE THREAD

**Issue by rockywind** [PJLab-ADG/DetZero#22]
Hi, thank you for sharing the great work.
The error is below.
![image](https://github.com/PJLab-ADG/DetZero/assets/14838781/34cdc7bf-45f6-44aa-aa3a-04ee0ab1348e)

The raw_pred_data structure is below.
![image](https://github.com/PJLab-ADG/DetZero/assets/14838781/d4ac6fee-c6be-4d55-8a38-de489958fee0)
The visualization script is below.
````
python visualizer.py  --data_path /SHFP12/xiaoquan.wang/01_bev/DetZero/01_refine_result/Vehicle_final.pkl
--seq_name 1024360143612057520_3580_000_3600_000
````

**Comment by zhutongseu1994** [comment]
I also encountered this problem, how did you solve this error?

**Comment by Annie990401** [comment]
Hi, I have the same error. However I add the --seq_name, I get the same error "str object has no attribute keys". Could you share your modification?

**Comment by SampWEI** [comment]
Same error, too. Any solutions here?

**Comment by Gmonster-24** [comment]
使用Vehicle_final_frame.pkl将Vehicle_final.pkl进行替换
