### ISSUE TITLE
waymo data processing

### ISSUE THREAD

**Issue by Annie990401** [PJLab-ADG/DetZero#44]
Hi, when I run the python -m detzero_det.datasets.waymo.waymo_preprocess --cfg_file tools/cfgs/det_dataset_cfgs/waymo_one_sweep.yaml --func create_waymo_infos to generate infos,  it gets stuck with no response. Is it normal? If it is, approximately how long dose it take to process the data? Looking forward to your reply.

![image](https://github.com/PJLab-ADG/DetZero/assets/144299223/48a7003a-b5cd-49be-9f63-1bc14189987d)

**Comment by superkoma** [comment]
Yes, it's normal. The processing time depends on your machine configuration. We provide multi-process setting, so you can speed up it with more workers.
Actually, it's quite early for me to remember, maybe 1-2 days.
