### ISSUE TITLE
Daemon / Refine for training set

### ISSUE THREAD

**Issue by Annie990401** [PJLab-ADG/DetZero#45]
I split train set in daemon, which PATH_TO_TRACKING_RESULT should be use. Because in tracking and detection part, the code only generate the val result. Should I generate result for training set?.

cd DetZero/daemon &&
python prepare_object_data.py --track_data_path <PATH_TO_TRACKING_RESULT> --split train

**Comment by superkoma** [comment]
Absolutely yes, you need to run the detection and tracking for train set, and then prepare the object data for training.
The command is right, you need to set `--split train`.

**Comment by Isaac-xie** [comment]
sorry, does this mean we need to use waymo's training set in the detection and tracking part?

**Comment by YoushaaMurhij** [comment]
@superkoma, @Isaac-xie, @Annie990401. I tried to run the detection and tracking for train set but I ran out of RAM.
How much RAM do I need to prepare the data for train split? and can I reduce the required memory usage for this step?
Thanks!
