### ISSUE TITLE
experiments on nuscenes

### ISSUE THREAD

**Issue by SISTMrL** [PJLab-ADG/DetZero#5]
hello, do you have any plan to do experiments on nuscenes datasets

**Comment by superkoma** [comment]
Yes, we have already conducted several experiments on nuScenes dataset, and our method could get performance gains compared to the baseline. Besides, we are trying to use more sensor data to further improve the performance. Maybe we will release the next multi-modal version in the future.

**Comment by SISTMrL** [comment]
thanks for your reply, i really looking forward to your multimodal version on nuscenes

**Comment by zhaowenZhou** [comment]
> 

Pretty insane that you try to extend it to multi modal and still release the code, amazing work!!!!

**Comment by AWDawson** [comment]
@superkoma Amazing work! Will you release the code based on nuscenes dataset?
